# Verzeichnis der Beiträge und Autor*innen

## Kapitel

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(readr)

kapitel <- read.csv2(file = "kapitel.csv")
colnames(kapitel) <- c("Autor*innen","Datum","Titel","Weitere Beitragende")

knitr::kable(kapitel)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
sorting_tasks <- read.csv2(file = "sorting_tasks.csv")
colnames(sorting_tasks) <- c("Autor*innen","Datum","Titel","Weitere Beitragende")

knitr::kable(sorting_tasks)
```

#```{r echo=FALSE, message=FALSE, warning=FALSE}
#baseknowledge_R <- read_delim("baseknowledge_R.csv", 
#    delim = ";", escape_double = FALSE, locale = locale(encoding = "ISO-8859-1"), 
#    trim_ws = TRUE)
#colnames(baseknowledge_R) <- c("Autor*innen","Datum","Titel","Weitere Beitragende")
#
#knitr::kable(baseknowledge_R)
#```

## Beiträge zu Fehlvorstellungen

```{r echo=FALSE, message=FALSE, warning=FALSE}
fehl_vorst <- read.csv2(file = "fehl_vorst.csv")
colnames(fehl_vorst) <- c("Autor*innen","Datum","Titel","Weitere Beitragende")

knitr::kable(fehl_vorst)
```

# Bibliographie

